baseURL = 'https://serj.kimmel.one'
languageCode = 'en-us'
title = 'Sergei Kimmel'
theme = 'lynx'

[params]
description = "Sergei Kimmel's contacts and references."

[author]
  name = 'Sergei Kimmel'
  headline = 'Golang/PHP Backend Software Developer'
  image = 'avatar.png'
  links = [
    { linkedin = "https://linkedin.com/in/sergei-kimmel" },
    { google = "mailto:kimmel.serj@gmail.com" },
    { facebook = "https://www.facebook.com/kimmel.serj" },
    { github = "https://github.com/kimmelserj" },
    { telegram = "https://t.me/kimmelserj" },
  ]

